name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2.0.1
      with:
        version: master

    - name: Test
      run: |
        zig build test

    - name: Fetch latest Vulkan SDK
      run: |
        wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-jammy.list https://packages.lunarg.com/vulkan/lunarg-vulkan-jammy.list
        sudo apt update
        sudo apt install shaderc libglfw3 libglfw3-dev

    - name: Fetch latest vk.xml
      run: |
        wget https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/main/xml/vk.xml

    - name: Build with latest zig & vk.xml
      run: |
        zig build -Dexample-registry=./vk.xml

    - name: Archive vk.zig
      uses: actions/upload-artifact@v2
      with:
        name: vk.zig
        path: zig-out/src/vk.zig
